# Generated by Django 4.0.2 on 2022-02-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_codedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codedata',
            old_name='category',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
