# Generated by Django 4.0.2 on 2022-02-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_category_codedata_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codedata',
            name='Issure',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='codedata',
            name='Code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
